### ISSUE TITLE
How do I run it

### ISSUE THREAD

**Issue by MatWaze** [franton/Xcode-Scripts#1]
Hello, I'm having problems understanding how to run the scripts. You said:

> I'm running this as part of a Casper / JAMF Pro policy to install Xcode. I deploy Xcode then run "finalise" script immediately afterwards. The "simulator" script is also run from Self Service, and it's using Terminal Notifier to provide feedback as to what's going on to the user. Good thing too, otherwise it'd just happily sit there and people would wonder if it's crashed or not.

How do I actually deploy Xcode? According to munki, I got Xcode11.3.1 file, where I added this postinstall_script:
```
<key>postinstall_script</key>
<string>#!/bin/sh

# make sure all users on this machine are members of the _developer group
/usr/sbin/dseditgroup -o edit -a everyone -t group _developer

# enable developer mode
/usr/sbin/DevToolsSecurity -enable

# accept Xcode license
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -license accept

# install embedded packages
for PKG in /Applications/Xcode.app/Contents/Resources/Packages/*.pkg; do
    /usr/sbin/installer -pkg "$PKG" -target /
done
</string>
```
And after this I don't know what to do. I tried running managedsoftwareupdate, but it required me to be root.

**Comment by franton** [comment]
Hi,

Latest Xcode is currently now 15.4. I don't think that version of Xcode you're using will even install on a relatively modern macOS version now.

The script is long out of date. I don't think it really works anymore with modern versions.

Unless you're running dangerously old versions of Xcode on dangerously old OS versions, this script and the version of Xcode you're trying to run likely will not work.

**Comment by MatWaze** [comment]
It's as you said, where I study we work on mac 10.14 and what's worse we don't have admin rights so it's hard to install something like Xcode

**Comment by franton** [comment]
I'm sorry for delayed reply. I am not well right now.

I haven't used Munki in close to nine years now. I believe the script above can be run via Munki after it deploys Xcode. I'm sorry I can't help more than that. Or you could wrap your Xcode installer into a bigger pkg with that script.

**Comment by MatWaze** [comment]
It's okay don't worry. Thank you very much and wish you will get better soon!
